### ISSUE TITLE
Issue with version .xml and with compiled .zip

### ISSUE THREAD

**Issue by bossehimself** [paynl/hikashop-plugin#2]
The zip file “Paynl-Hikashop-v3.2.7.zip” cannot be used as an installer within Joomla since it is compiled incorrectly.
When extracting, you will notice the subfolder 'paynl' does not contain any data.
You can offourse use the "source code" and create your own .zip for upload into Joomla but most of your customers are going to try with the non-working default .zip and will end up contacting your paynl support.
Furthermore, the file "payment.xml" contains the following 2 lines from a previous version of this plugin:

<creationDate>July 2014</creationDate>
<version>3.2.4</version>

You might want to updates these lines as well in your version 3.2.7 since Joomla backend will show an old version number, even when the newest update is installed.

**Comment by woutse** [comment]
Thanks for letting us now! We updated, tested and uploaded a new zip file. This should work fine now!

**Comment by bossehimself** [comment]
> Thanks for letting us now! We updated, tested and uploaded a new zip file. This should work fine now!

Works like a charm! Thanks for the very quick reply!
